Support i18next 22
maximLeontiev/i18next-endings-postprocessor pull request #5
Opened 2023-06-21 06:04 UTC by igorkamyshev

- Написал тесты на базовый кейс
- Настроил CI на GitHub Actions, чтобы эти тесты запускались
- Починил работу плагина с i18next@22

2023-06-21 06:13 UTC, AlexandrHoroshih approved these changes
🔥

2023-06-26 11:43 UTC, maximLeontiev requested changes
Один из кейсов которые этот постпроцессор покрывает, это использование нескольких значений для плюрализации в одной строке. Например – `Мы нашли всего 47 билетов, из которых 21 билет подходит лучше всего`.

В случае перевода его `one|few|many|other`, такая возможность теряется. Придется бить строку на составные части.

2023-06-26 11:44 UTC, igorkamyshev commented
> Один из кейсов которые этот постпроцессор покрывает, это использование нескольких значений для плюрализации в одной строке. Например – `Мы нашли всего 47 билетов, из которых 21 билет подходит лучше всего`.
> 
> В случае перевода его `one|few|many|other`, такая возможность теряется. Придется бить строку на составные части.

Можешь написать тест-кейс? Можно сюда. Без тестов очень сложно править поведение.

2023-06-26 11:47 UTC, igorkamyshev commented
@maximLeontiev добавил строку, которую ты написал в ревью в тест-кейсы. Тесты по прежнему проходят — https://github.com/maximLeontiev/i18next-endings-postprocessor/pull/5/commits/e4ba9d9841399080771714d962b5b3cae210e112

2023-06-27 05:27 UTC, maximLeontiev approved these changes
Угу спасиб! Тогда ок

2023-06-27 05:28 UTC, merged